baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en
name: 'Beer Affordability'
primary: true
siteGroup: c02cb380-908d-4c39-975d-e97bc52d6111 # BeerAffordability
sortOrder: 1
