allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  b1c4a88a-6b9e-4b41-b9ca-07776dbea45d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-23T22:36:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bdd844fd-92f8-49e3-a925-aebff7bc58a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3399c487-8445-4f3d-beca-e654ee15f3f6
        userCondition: null
    thumbFieldKey: null
handle: country
hasTitleField: true
icon: null
name: Country
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
