allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  bdd28247-65a4-4346-82e0-f7dedf75f093:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-23T23:11:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 537ff796-956c-45d6-a5d3-206400c6e34b # Link
            handle: null
            instructions: null
            label: __blank__
            oldFieldUid: 537ff796-956c-45d6-a5d3-206400c6e34b # Link
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bfd4995-9e7e-47d4-af05-a1f1e4da4651
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7c0da5f-d73a-4946-b9e4-dada1b42afa3
        userCondition: null
    thumbFieldKey: null
handle: navItem
hasTitleField: false
icon: null
name: 'Nav Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{navLink.label}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
