defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ca0db582-a1c8-44f6-96fa-4b979fb2b135 # Country
handle: countries
maxAuthors: 1
minAuthors: 1
name: Countries
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6b9e4bf0-09c7-4a60-859e-53a218da1851: # BeerAffordability
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
