isPublic: false
name: Endpoint
scope:
  - 'sites.6b9e4bf0-09c7-4a60-859e-53a218da1851:read' # Beer Affordability
  - 'sections.05ccd371-b38d-424f-8ab8-b0af4a3da046:read' # Countries
  - 'sections.e7450e6b-2ab7-4769-bd6d-5fd8a06bdebd:read' # Datapoints
  - 'sections.41f64f30-c0dc-44b6-99ff-1e6ce5ab9ebf:read' # Pages
  - 'sections.9485fef3-79b0-404e-adc9-55e806f10318:read' # Quarters
  - 'nestedentryfields.c664c346-5d38-45f3-865a-00f913d4a977:read' # Intro
  - 'nestedentryfields.6d075d2a-2731-4b2b-8b36-3153c389fbf2:read' # Navigation
  - 'globalsets.c9fa2b5e-8aea-46d5-a1de-c417c7cbab7c:read' # Footer
  - 'crelte.all:read'
